name: docker

on:
  workflow_call:
    inputs:
      image-name:
        description: "image name"
        required: true
        type: string

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: build it
        run: |
          echo IMAGE-NAME: ${{ inputs.image-name }} ${{github.run_number}} ${{github.sha}}
